/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    bikes: Bike;
    categories: Category;
    pages: Page;
    posts: Post;
    faqs: Faq;
    testimonials: Testimonial;
    dealers: Dealer;
    'test-ride-bookings': TestRideBooking;
    reservations: Reservation;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    bikes: BikesSelect<false> | BikesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    dealers: DealersSelect<false> | DealersSelect<true>;
    'test-ride-bookings': TestRideBookingsSelect<false> | TestRideBookingsSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'bn') | ('en' | 'bn')[];
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
    'vehicle-types': VehicleType;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'vehicle-types': VehicleTypesSelect<false> | VehicleTypesSelect<true>;
  };
  locale: 'en' | 'bn';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bikes".
 */
export interface Bike {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Used in the URL, e.g. /models/velocity-x1
   */
  slug: string;
  tagline?: string | null;
  description?: string | null;
  category: 'commuter' | 'sport' | 'cargo';
  vehicleType: 'ebike' | 'escooter' | 'ecycle';
  status: 'available' | 'comingSoon';
  featured?: boolean | null;
  badge?: string | null;
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional product video
   */
  video?: (string | null) | Media;
  /**
   * Paint color hex codes shown in the variant selector
   */
  colorSwatches?:
    | {
        hex: string;
        id?: string | null;
      }[]
    | null;
  specs: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  range?: string | null;
  topSpeed?: string | null;
  motor?: string | null;
  battery?: string | null;
  chargeTime?: string | null;
  /**
   * Starting price in BDT (৳)
   */
  basePrice: number;
  emiEligible?: boolean | null;
  variants?:
    | {
        colorName: string;
        /**
         * Price in BDT (৳)
         */
        price: number;
        sku?: string | null;
        inStock: 'inStock' | 'preOrder' | 'soldOut';
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Downloadable PDF spec sheet
   */
  specSheet?: (string | null) | Media;
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Required for accessibility (WCAG 2.1 AA). Describe the image in one line.
   */
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  blocks?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            backgroundImage?: (string | null) | Media;
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            features?:
              | {
                  icon?:
                    ('battery' | 'range' | 'speed' | 'chargeTime' | 'eco' | 'cost' | 'service' | 'warranty') | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            images?:
              | {
                  image: string | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            text?: string | null;
            buttons?:
              | {
                  label: string;
                  url: string;
                  style?: ('primary' | 'secondary') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            rows?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'specTable';
          }
        | {
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsSection';
          }
        | {
            heading?: string | null;
            category?: ('all' | 'general' | 'battery' | 'warranty' | 'buying' | 'riding') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqSection';
          }
      )[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  excerpt?: string | null;
  coverImage?: (string | null) | Media;
  category?: (string | null) | Category;
  author?: (string | null) | User;
  publishDate?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags?: string[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  roles: ('admin' | 'editor' | 'sales')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: string;
  category?: ('general' | 'battery' | 'warranty' | 'buying' | 'riding') | null;
  /**
   * Sort order within category (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  quote: string;
  photo?: (string | null) | Media;
  rating?: number | null;
  modelPurchased?: (string | null) | Bike;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers".
 */
export interface Dealer {
  id: string;
  name: string;
  address: string;
  division: 'dhaka' | 'chattogram' | 'khulna' | 'rajshahi' | 'sylhet' | 'barishal' | 'rangpur' | 'mymensingh';
  district: string;
  /**
   * Stored as [longitude, latitude]
   *
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  phone: string;
  hours?: string | null;
  servicesOffered: ('sales' | 'service' | 'charging')[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Test ride requests submitted from the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-ride-bookings".
 */
export interface TestRideBooking {
  id: string;
  name: string;
  /**
   * BD mobile number, e.g. +880 1XXXXXXXXX
   */
  phone: string;
  email?: string | null;
  model: string | Bike;
  dealer?: (string | null) | Dealer;
  city?: string | null;
  preferredDate?: string | null;
  status: 'new' | 'contacted' | 'scheduled' | 'completed' | 'lost';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reserve / pre-order interest submitted from the website (no live payment in Phase 1).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: string;
  name: string;
  /**
   * BD mobile number, e.g. +880 1XXXXXXXXX
   */
  phone: string;
  email?: string | null;
  model: string | Bike;
  variant?: string | null;
  depositInterest?: boolean | null;
  depositPaid?: boolean | null;
  status: 'new' | 'contacted' | 'converted' | 'lost';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'bikes';
        value: string | Bike;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'dealers';
        value: string | Dealer;
      } | null)
    | ({
        relationTo: 'test-ride-bookings';
        value: string | TestRideBooking;
      } | null)
    | ({
        relationTo: 'reservations';
        value: string | Reservation;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bikes_select".
 */
export interface BikesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  category?: T;
  vehicleType?: T;
  status?: T;
  featured?: T;
  badge?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  video?: T;
  colorSwatches?:
    | T
    | {
        hex?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  range?: T;
  topSpeed?: T;
  motor?: T;
  battery?: T;
  chargeTime?: T;
  basePrice?: T;
  emiEligible?: T;
  variants?:
    | T
    | {
        colorName?: T;
        price?: T;
        sku?: T;
        inStock?: T;
        image?: T;
        id?: T;
      };
  specSheet?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              text?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        specTable?:
          | T
          | {
              heading?: T;
              rows?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialsSection?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        faqSection?:
          | T
          | {
              heading?: T;
              category?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  category?: T;
  author?: T;
  publishDate?: T;
  content?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  quote?: T;
  photo?: T;
  rating?: T;
  modelPurchased?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers_select".
 */
export interface DealersSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  division?: T;
  district?: T;
  location?: T;
  phone?: T;
  hours?: T;
  servicesOffered?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-ride-bookings_select".
 */
export interface TestRideBookingsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  model?: T;
  dealer?: T;
  city?: T;
  preferredDate?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  model?: T;
  variant?: T;
  depositInterest?: T;
  depositPaid?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  tagline?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  address?: string | null;
  navLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'linkedin' | 'tiktok' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The /dealers page. Any field left empty falls back to the built-in translation.
   */
  dealerPage?: {
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
    heroImage?: (string | null) | Media;
    benefitsEyebrow?: string | null;
    benefitsHeading?: string | null;
    benefits?:
      | {
          /**
           * A single emoji, e.g. 💰
           */
          icon?: string | null;
          title: string;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Shown in the green band on the dealer page. Centre and division counts are calculated from the Dealers collection.
   */
  networkStats?: {
    /**
     * Happy riders, e.g. 50000. Rendered as “50,000+”.
     */
    riders?: number | null;
    /**
     * Average rating out of 5, e.g. 4.8.
     */
    rating?: number | null;
  };
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOGImage?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  /**
   * Rotating full-bleed slides. Leave empty to use the built-in copy and the featured models’ own photography.
   */
  slides?:
    | {
        /**
         * Line breaks are preserved.
         */
        title: string;
        subtitle?: string | null;
        /**
         * Small pill above the title, e.g. “New 2026 line”.
         */
        badge?: string | null;
        image?: (string | null) | Media;
        /**
         * Optional. Points the slide’s primary button at this model and borrows its hero image when none is set above.
         */
        bike?: (string | null) | Bike;
        id?: string | null;
      }[]
    | null;
  /**
   * Green band under the hero. Leave empty to count models and dealerships automatically.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  rangeEyebrow?: string | null;
  rangeHeading?: string | null;
  /**
   * Hand-pick the models shown on the home page. Leave empty to show the featured models.
   */
  rangeBikes?: (string | Bike)[] | null;
  appEyebrow?: string | null;
  appHeading?: string | null;
  appBody?: string | null;
  appPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the right of the banner. Falls back to the built-in app mockup when empty.
   */
  appImage?: (string | null) | Media;
  appStoreUrl?: string | null;
  appStoreLabel?: string | null;
  playStoreUrl?: string | null;
  playStoreLabel?: string | null;
  missionEyebrow?: string | null;
  missionHeading?: string | null;
  missionBody?: string | null;
  missionImage?: (string | null) | Media;
  featuresEyebrow?: string | null;
  featuresHeading?: string | null;
  features?:
    | {
        /**
         * A single emoji, e.g. 🔋
         */
        icon?: string | null;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaHeading?: string | null;
  ctaBody?: string | null;
  ctaLabel?: string | null;
  /**
   * Site-relative, e.g. /test-ride — the locale is added for you.
   */
  ctaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-types".
 */
export interface VehicleType {
  id: string;
  ecycle?: {
    /**
     * Page title. Defaults to “E-Cycle”.
     */
    heading?: string | null;
    /**
     * One line under the title, over the hero photo.
     */
    subtitle?: string | null;
    /**
     * Intro paragraph in the white band below the hero.
     */
    body?: string | null;
    /**
     * Leave empty to borrow the first model’s hero photo.
     */
    heroImage?: (string | null) | Media;
  };
  escooter?: {
    /**
     * Page title. Defaults to “E-Scooter”.
     */
    heading?: string | null;
    /**
     * One line under the title, over the hero photo.
     */
    subtitle?: string | null;
    /**
     * Intro paragraph in the white band below the hero.
     */
    body?: string | null;
    /**
     * Leave empty to borrow the first model’s hero photo.
     */
    heroImage?: (string | null) | Media;
  };
  ebike?: {
    /**
     * Page title. Defaults to “E-Bike”.
     */
    heading?: string | null;
    /**
     * One line under the title, over the hero photo.
     */
    subtitle?: string | null;
    /**
     * Intro paragraph in the white band below the hero.
     */
    body?: string | null;
    /**
     * Leave empty to borrow the first model’s hero photo.
     */
    heroImage?: (string | null) | Media;
  };
  /**
   * Green strip shown at the foot of all three pages. Leave empty to reuse the home page pillars.
   */
  featureStrip?:
    | {
        /**
         * A single emoji, e.g. 🔋
         */
        icon?: string | null;
        title: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Small print beside the model count, e.g. ex-showroom city.
   */
  priceNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  dealerPage?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        heroImage?: T;
        benefitsEyebrow?: T;
        benefitsHeading?: T;
        benefits?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  networkStats?:
    | T
    | {
        riders?: T;
        rating?: T;
      };
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOGImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        title?: T;
        subtitle?: T;
        badge?: T;
        image?: T;
        bike?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  rangeEyebrow?: T;
  rangeHeading?: T;
  rangeBikes?: T;
  appEyebrow?: T;
  appHeading?: T;
  appBody?: T;
  appPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  appImage?: T;
  appStoreUrl?: T;
  appStoreLabel?: T;
  playStoreUrl?: T;
  playStoreLabel?: T;
  missionEyebrow?: T;
  missionHeading?: T;
  missionBody?: T;
  missionImage?: T;
  featuresEyebrow?: T;
  featuresHeading?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  ctaHeading?: T;
  ctaBody?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-types_select".
 */
export interface VehicleTypesSelect<T extends boolean = true> {
  ecycle?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        body?: T;
        heroImage?: T;
      };
  escooter?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        body?: T;
        heroImage?: T;
      };
  ebike?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        body?: T;
        heroImage?: T;
      };
  featureStrip?:
    | T
    | {
        icon?: T;
        title?: T;
        id?: T;
      };
  priceNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}